<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Branches_model extends App_Model
{
    

    public function get($id='')
    {
        if($id){
            $this->db->where('branch_id',$id);
            return $this->db->get(db_prefix() . 'branches')->row();
        }
        $this->db->order_by('branch_name', 'asc');

        return $this->db->get(db_prefix() . 'branches')->result();
        // $result = $this->db->get('tblbranches')->result();
        
        // return $result;
    }

    public function add($data){
        $this->db->insert(db_prefix() . 'branches', $data);
        $id = $this->db->insert_id();
        return $id;
    }

    public function update($id,$data){
        $this->db->where('branch_id ', $id);
        $this->db->update(db_prefix() . 'branches', $data);

        if ($this->db->affected_rows() > 0) {
            return true;
        }
        return false;
    }

    public function delete($id){
       
        
        $this->db->where('branch_id', $id);
        $this->db->delete(db_prefix() . 'branch_options');

        $this->db->where('branch_id', $id);
        $this->db->delete(db_prefix() . 'branches');

        return true;

    }
    // public function add_new_branch_options($id){
        
    //     $default_options=array(
    //         array('option_id'=>1,'value'=>'Y-m-d|%Y-%m-%d','autoload'=>1),
    //         array('option_id'=>2,'value'=>'','autoload'=>1),
    //         array('option_id'=>3,'value'=>'1','autoload'=>1),
    //         array('option_id'=>4,'value'=>'4','autoload'=>1),
    //         array('option_id'=>5,'value'=>'.jpg,.png,.pdf,.doc,.zip,.rar','autoload'=>1),
    //         array('option_id'=>6,'value'=>'1','autoload'=>1),
    //         array('option_id'=>7,'value'=>'1','autoload'=>1),
    //         array('option_id'=>8,'value'=>'','autoload'=>1),
    //         array('option_id'=>9,'value'=>'','autoload'=>1),
    //         array('option_id'=>10,'value'=>'{company_name}<br />\r\n      {address}<br />\r\n      {city} {state}<br />\r\n      {country_code} {zip_code}<br />\r\n      {vat_number_with_label}','autoload'=>0),
    //         array('option_id'=>11,'value'=>'','autoload'=>1),
    //         array('option_id'=>12,'value'=>'','autoload'=>1),
    //         array('option_id'=>13,'value'=>'utf-8','autoload'=>1),
    //         array('option_id'=>14,'value'=>'Europe/Berlin','autoload'=>1),
    //         array('option_id'=>15,'value'=>'finishizer','autoload'=>1),
    //         array('option_id'=>16,'value'=>'','autoload'=>1),
    //         array('option_id'=>17,'value'=>25,'autoload'=>1),
    //         array('option_id'=>18,'value'=>'','autoload'=>1),
    //         array('option_id'=>19,'value'=>'0','autoload'=>1),
    //         array('option_id'=>20,'value'=>'1','autoload'=>1),
    //         array('option_id'=>21,'value'=>'','autoload'=>1),
    //         array('option_id'=>22,'option_id'=>21,'value'=>'1','autoload'=>1),
    //         array('option_id'=>23,'value'=>'10','autoload'=>1),
    //         array('option_id'=>24,'value'=>'4','autoload'=>1),
    //         array('option_id'=>25,'value'=>'INV-','autoload'=>1),
    //         array('option_id'=>26,'value'=>'.','autoload'=>1),
    //         array('option_id'=>27,'value'=>',','autoload'=>1),
    //         array('option_id'=>28,'value'=>'','autoload'=>1),
    //         array('option_id'=>29,'value'=>'','autoload'=>1),
    //         array('option_id'=>30,'value'=>'','autoload'=>1),
    //         array('option_id'=>31,'value'=>'','autoload'=>1),
    //         array('option_id'=>32,'value'=>'','autoload'=> 1),
    //         array('option_id'=>33,'value'=>'','autoload'=> 1),
    //         array('option_id'=>34,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>35,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>36,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>37,'value'=> 'english','autoload'=> 1),
    //         array('option_id'=>38,'value'=> '1','autoload'=> 1),
    //         array('option_id'=>39,'value'=> '1','autoload'=> 1),
    //         array('option_id'=>40,'value'=> '3','autoload'=> 1),
    //         array('option_id'=>41,'value'=>'21','autoload'=> 1),
    //         array('option_id'=>42,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>43,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>44,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>45,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>46,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>47,'value'=> '10','autoload'=> 1),
    //         array('option_id'=>48,'value'=>'EST-','autoload'=> 1),
    //         array('option_id'=>49,'value'=> '1', 'autoload'=>0),
    //         array('option_id'=>50,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>51,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>52,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>53,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>54,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>55,'value'=>'','autoload'=> 1),
    //         array('option_id'=>56,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>57,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>58,'value'=>'','autoload'=> 1),
    //         array('option_id'=>59,'value'=>'','autoload'=> 1),
    //         array('option_id'=>60,'value'=>'2','autoload'=> 1),
    //         array('option_id'=>61,'value'=>'','autoload'=> 1),
    //         array('option_id'=>62,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>63,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>64,'value'=>'','autoload'=> 1),
    //         array('option_id'=>65,'value'=>'','autoload'=> 1),
    //         array('option_id'=>66,'value'=>'','autoload'=> 1),
    //         array('option_id'=>67,'value'=>'','autoload'=> 1),
    //         array('option_id'=>68,'value'=>'30','autoload'=> 1),
    //         array('option_id'=>69,'value'=>'','autoload'=> 1),
    //         array('option_id'=>70,'value'=>'','autoload'=> 1),
    //         array('option_id'=>71,'value'=>'a:0:{}','autoload'=> 1),
    //         array('option_id'=>72,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>73,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>74,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>75,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>76,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>77,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>78,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>79,'value'=>'4','autoload'=> 1),
    //         array('option_id'=>80,'value'=>'','autoload'=> 1),
    //         array('option_id'=>81,'value'=>'','autoload'=> 1),
    //         array('option_id'=>82,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>83,'value'=> '4','autoload'=> 1),
    //         array('option_id'=>84,'value'=>'a:6:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";i:3;s:1:\"4\";i:4;s:1:\"5\";i:5;s:1:\"6\";}','autoload'=> 1),
    //         array('option_id'=>85,'value'=>'150','autoload'=> 1),
    //         array('option_id'=>86,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>87,'value'=>'','autoload'=> 1),
    //         array('option_id'=>88,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>89,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>90,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>91,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>92,'value'=>'dayGridMonth','autoload'=> 1),
    //         array('option_id'=>93,'value'=>'2','autoload'=> 1),
    //         array('option_id'=>94,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>95,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>96,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>97,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>98,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>99,'value'=>'10','autoload'=> 1),
    //         array('option_id'=>100,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>101,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>102,'value'=>'50','autoload'=> 1),
    //         array('option_id'=>103,'value'=>'2','autoload'=> 1),
    //         array('option_id'=>104,'value'=>'freesans','autoload'=> 1),
    //         array('option_id'=>105,'value'=>'#323a45','autoload'=> 1),
    //         array('option_id'=>106,'value'=>'#ffffff','autoload'=> 1),
    //         array('option_id'=>107,'value'=>'10','autoload'=> 1),
    //         array('option_id'=>108,'value'=>'leadorder','autoload'=> 1),
    //         array('option_id'=>109,'value'=>'asc','autoload'=> 1),
    //         array('option_id'=>110,'value'=>'.png,.jpg,.pdf,.doc,.docx,.xls,.xlsx,.zip,.rar,.txt','autoload'=> 1),
    //         array('option_id'=>111,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>112,'value'=>'smtp','autoload'=> 1),
    //         array('option_id'=>113,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>114,'value'=>'','autoload'=> 1),
    //         array('option_id'=>115,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>116,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>117,'value'=>'','autoload'=> 1),
    //         array('option_id'=>118,'value'=>'','autoload'=> 1),
    //         array('option_id'=>119,'value'=>'','autoload'=> 1),
    //         array('option_id'=>120,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>121,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>122,'value'=>'#FF6F00','autoload'=> 1),
    //         array('option_id'=>123,'value'=>'#FF6F00','autoload'=> 1),
    //         array('option_id'=>124,'value'=>'#84c529','autoload'=> 1),
    //         array('option_id'=>125,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>126,'value'=>'#03A9F4','autoload'=> 1),
    //         array('option_id'=>127,'value'=>'#B72974','autoload'=> 1),
    //         array('option_id'=>128,'value'=>'#B72974','autoload'=> 1),
    //         array('option_id'=>129,'value'=>'','autoload'=> 1),
    //         array('option_id'=>130,'value'=>'1','autoload'=> 1),            
    //         array('option_id'=>131,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>132,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>133,'value'=>'7','autoload'=> 1),
    //         array('option_id'=>134,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>135,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>136,'value'=>'pipeline_order','autoload'=> 1),
    //         array('option_id'=>137,'value'=>'asc','autoload'=> 1),
    //         array('option_id'=>138,'value'=>'pipeline_order','autoload'=> 1),
    //         array('option_id'=>139,'value'=>'asc','autoload'=> 1),
    //         array('option_id'=>140,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>141,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>142,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>143,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>144,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>145,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>146,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>147,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>148,'value'=>'0','autoload'=> 1), 
    //         array('option_id'=>149,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>150,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>151,'value'=>'0','autoload'=> 0),  
    //         array('option_id'=>152,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>153,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>154,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>155,'value'=>'50','autoload'=> 1),  
    //         array('option_id'=>156,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>157,'value'=>'50','autoload'=> 1),  
    //         array('option_id'=>158,'value'=>'50','autoload'=> 1),  
    //         array('option_id'=>159,'value'=>'PRO-','autoload'=> 1),  
    //         array('option_id'=>160,'value'=>'6','autoload'=> 1),  
    //         array('option_id'=>161,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>162,'value'=>'4','autoload'=> 1),  
    //         array('option_id'=>163,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>164,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>165,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>166,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>167,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>168,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>169,'value'=>'21','autoload'=> 1),  
    //         array('option_id'=>170,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>171,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>172,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>173,'value'=>'7','autoload'=> 1),  
    //         array('option_id'=>174,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>175,'value'=>'24','autoload'=> 1),              
    //         array('option_id'=>176,'value'=>'1','autoload'=> 1),              
    //         array('option_id'=>177,'value'=>'0','autoload'=> 1),              
    //         array('option_id'=>178,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>179,'value'=>'<!doctype html>\r\n      <html>\r\n      <head>\r\n      <meta name=\"viewport\" content=\"width=device-width\" />\r\n      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n      <style>\r\n      body {\r\n        background-color: #f6f6f6;\r\n        font-family: Tajawal,sans-serif;\r\n        -webkit-font-smoothing: antialiased;\r\n        font-size: 14px;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        padding: 0;\r\n        -ms-text-size-adjust: 100%;\r\n        -webkit-text-size-adjust: 100%;\r\n      }\r\n      table {\r\n        border-collapse: separate;\r\n        mso-table-lspace: 0pt;\r\n        mso-table-rspace: 0pt;\r\n        width: 100%;\r\n      }\r\n      table td {\r\n        font-family: Tajawal,sans-serif;\r\n        font-size: 14px;\r\n        vertical-align: top;\r\n      }\r\n      /* -------------------------------------\r\n      BODY & CONTAINER\r\n      ------------------------------------- */\r\n      .body {\r\n        background-color: #f6f6f6;\r\n        width: 100%;\r\n      }\r\n      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\r\n      \r\n      .container {\r\n        display: block;\r\n        margin: 0 auto !important;\r\n        /* makes it centered */\r\n        max-width: 680px;\r\n        padding: 10px;\r\n        width: 680px;\r\n      }\r\n      /* This should also be a block element, so that it will fill 100% of the .container */\r\n      \r\n      .content {\r\n        box-sizing: border-box;\r\n        display: block;\r\n        margin: 0 auto;\r\n        max-width: 680px;\r\n        padding: 10px;\r\n      }\r\n      /* -------------------------------------\r\n      HEADER, FOOTER, MAIN\r\n      ------------------------------------- */\r\n      \r\n      .main {\r\n        background: #fff;\r\n        border-radius: 3px;\r\n        width: 100%;\r\n      }\r\n      .wrapper {\r\n        box-sizing: border-box;\r\n        padding: 20px;\r\n      }\r\n      .footer {\r\n        clear: both;\r\n        padding-top: 10px;\r\n        text-align: center;\r\n        width: 100%;\r\n      }\r\n      .footer td,\r\n      .footer p,\r\n      .footer span,\r\n      .footer a {\r\n        color: #999999;\r\n        font-size: 12px;\r\n        text-align: center;\r\n      }\r\n      hr {\r\n        border: 0;\r\n        border-bottom: 1px solid #f6f6f6;\r\n        margin: 20px 0;\r\n      }\r\n      /* -------------------------------------\r\n      RESPONSIVE AND MOBILE FRIENDLY STYLES\r\n      ------------------------------------- */\r\n      \r\n      @media only screen and (max-width: 620px) {\r\n        table[class=body] .content {\r\n          padding: 0 !important;\r\n        }\r\n        table[class=body] .container {\r\n          padding: 0 !important;\r\n          width: 100% !important;\r\n        }\r\n        table[class=body] .main {\r\n          border-left-width: 0 !important;\r\n          border-radius: 0 !important;\r\n          border-right-width: 0 !important;\r\n        }\r\n      }\r\n      </style>\r\n      </head>\r\n      <body class=\"\">\r\n      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\r\n      <tr>\r\n      <td>&nbsp;</td>\r\n      <td class=\"container\">\r\n      <div class=\"content\">\r\n      <!-- START CENTERED WHITE CONTAINER -->\r\n      <table class=\"main\">\r\n      <!-- START MAIN CONTENT AREA -->\r\n      <tr>\r\n      <td class=\"wrapper\">\r\n      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n      <tr>\r\n      <td>','autoload'=> 1),
    //         array('option_id'=>180,'value'=>'1','autoload'=> 0),  
    //         array('option_id'=>181,'value'=>'1','autoload'=> 0),  
    //         array('option_id'=>182,'value'=>'','autoload'=> 0),  
    //         array('option_id'=>183,'value'=>'</td>\r\n      </tr>\r\n      </table>\r\n      </td>\r\n      </tr>\r\n      <!-- END MAIN CONTENT AREA -->\r\n      </table>\r\n      <!-- START FOOTER -->\r\n      <div class=\"footer\">\r\n      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n      <tr>\r\n      <td class=\"content-block\">\r\n      <span>{companyname}</span>\r\n      </td>\r\n      </tr>\r\n      </table>\r\n      </div>\r\n      <!-- END FOOTER -->\r\n      <!-- END CENTERED WHITE CONTAINER -->\r\n      </div>\r\n      </td>\r\n      <td>&nbsp;</td>\r\n      </tr>\r\n      </table>\r\n      </body>\r\n      </html>','autoload'=> 1),  
    //         array('option_id'=>184,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>185,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>186,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>187,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>188,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>189,'value'=>'A4-PORTRAIT','autoload'=> 1),  
    //         array('option_id'=>190,'value'=>'','autoload'=> 1),  
    //         array('option_id'=>191,'value'=>'to_all','autoload'=> 1),  
    //         array('option_id'=>192,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>193,'value'=>'1','autoload'=> 0),  
    //         array('option_id'=>194,'value'=>'modal-lg','autoload'=> 1),  
    //         array('option_id'=>195,'value'=>'modal-lg','autoload'=> 1),  
    //         array('option_id'=>196,'value'=> '0','autoload'=> 1),  
    //         array('option_id'=>197,'value'=> '0','autoload'=> 1),  
    //         array('option_id'=>198,'value'=>'1','autoload'=> 0),  
    //         array('option_id'=>199,'value'=>'{company_name}<br />\r\n      {street}<br />\r\n      {city} {state}<br />\r\n      {country_code} {zip_code}<br />\r\n      {vat_number_with_label}','autoload'=> 0),  
    //         array('option_id'=>200,'value'=>'1','autoload'=> 0),  
    //         array('option_id'=>201,'value'=>'3','autoload'=> 1),  
    //         array('option_id'=>202,'value'=>'auto','autoload'=> 1),  
    //         array('option_id'=>203,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>204,'value'=>'0','autoload'=> 1),  
    //         array('option_id'=>205,'value'=>'','autoload'=> 1),              
    //         array('option_id'=>206,'value'=>'0','autoload'=> 1),              
    //         array('option_id'=>207,'value'=>'{proposal_to}<br />\r\n      {address}<br />\r\n      {city} {state}<br />\r\n      {country_code} {zip_code}<br />\r\n      {phone}<br />\r\n      {email}','autoload'=> 0),              
    //         array('option_id'=>208,'value'=>'asc','autoload'=> 1),  
    //         array('option_id'=>209,'value'=>'generate_and_send','autoload'=> 0),
    //         array('option_id'=>210,'value'=>'','autoload'=> 0),
    //         array('option_id'=>211,'value'=>'','autoload'=> 0),
    //         array('option_id'=>212,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>213,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>214,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>215,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>216,'value'=>'','autoload'=> 1),
    //         array('option_id'=>217,'value'=>'','autoload'=> 1),
    //         array('option_id'=>218,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>219,'value'=>'CN-','autoload'=> 1),
    //         array('option_id'=>220,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>221,'value'=>'A4-PORTRAIT','autoload'=> 1),
    //         array('option_id'=>222,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>223,'value'=>'1','autoload'=>1),
    //         array('option_id'=>224,'value'=>'1','autoload'=>1),
    //         array('option_id'=>225,'value'=>'1','autoload'=>1),
    //         array('option_id'=>226,'value'=>'1','autoload'=>1),
    //         array('option_id'=>227,'value'=>'1','autoload'=>1),
    //         array('option_id'=>228,'value'=>'1','autoload'=>1),
    //         array('option_id'=>229,'value'=>'1','autoload'=>1),
    //         array('option_id'=>230,'value'=>'1','autoload'=>1),
    //         array('option_id'=>231,'value'=>'1','autoload'=>1),
    //         array('option_id'=>232,'value'=>'1','autoload'=>1),
    //         array('option_id'=>233,'value'=>'1','autoload'=>1),
    //         array('option_id'=>234,'value'=>'21','autoload'=> 1),
    //         array('option_id'=>235,'value'=>'21','autoload'=> 1),
    //         array('option_id'=>236,'value'=>'21','autoload'=> 1),
    //         array('option_id'=>237,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>238,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>239,'value'=>'By clicking on \"Sign\", I consent to be legally bound by this electronic representation of my signature.','autoload'=> 1),
    //         array('option_id'=>240,'value'=>'1','autoload'=> 1),  
    //         array('option_id'=>241,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>242,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>243,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>244,'value'=>'send_invoice_and_receipt','autoload'=> 1),
    //         array('option_id'=>245,'value'=>'phpmailer','autoload'=> 1),
    //         array('option_id'=>246,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>247,'value'=>'','autoload'=> 1),
    //         array('option_id'=>248,'value'=>'','autoload'=> 1),
    //         array('option_id'=>249,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>250,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>251,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>252,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>253,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>254,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>255,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>256,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>257,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>258,'value'=>'','autoload'=> 1),
    //         array('option_id'=>259,'value'=>'','autoload'=> 1),
    //         array('option_id'=>260,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>261,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>262,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>263,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>264,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>265,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>266,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>267,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>268,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>269,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>270,'value'=>'1','autoload'=> 1),   
    //         array('option_id'=>271,'value'=>'0','autoload'=> 1), 
    //         array('option_id'=>272,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>273,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>274,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>275,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>276,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>277,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>278,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>279,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>280,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>281,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>282,'value'=>'all','autoload'=> 0),
    //         array('option_id'=>283,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>284,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>285,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>286,'value'=>'["email"]','autoload'=> 1),
    //         array('option_id'=>287,'value'=>'','autoload'=> 1),
    //         array('option_id'=>288,'value'=>'','autoload'=> 1),
    //         array('option_id'=>289,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>290,'value'=>'','autoload'=> 1),
    //         array('option_id'=>291,'value'=>'','autoload'=> 1),
    //         array('option_id'=>292,'value'=>'','autoload'=> 1),
    //         array('option_id'=>293,'value'=>'','autoload'=> 1),
    //         array('option_id'=>294,'value'=>'1','autoload'=> 0),
    //         array('option_id'=>295,'value'=>'','autoload'=> 1),
    //         array('option_id'=>296,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>297,'value'=>'true','autoload'=> 1),
    //         array('option_id'=>298,'value'=>'21','autoload'=> 1),
    //         array('option_id'=>299,'value'=>'0', 'autoload'=>1),
    //         array('option_id'=>300,'value'=>'1', 'autoload'=>1),
    //         array('option_id'=>301,'value'=>'0', 'autoload'=>1),
    //         array('option_id'=>302,'value'=>'5', 'autoload'=>1),
    //         array('option_id'=>303,'value'=>'','autoload'=> 1),   
    //         array('option_id'=>304,'value'=>'0','autoload'=> 1), 
    //         array('option_id'=>305,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>306,'value'=>'2','autoload'=> 1),
    //         array('option_id'=>307,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>308,'value'=>'true','autoload'=> 1),
    //         array('option_id'=>309,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>310,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>311,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>312,'value'=>'8','autoload'=> 1),
    //         array('option_id'=>313,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>314,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>315,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>316,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>317,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>318,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>319,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>320,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>321,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>322,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>323,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>324,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>325,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>326,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>327,'value'=>'', 'autoload'=>1),
    //         array('option_id'=>328,'value'=>'1','autoload'=> 1),
    //         array('option_id'=>329,'value'=>'0','autoload'=> 1),
    //         array('option_id'=>330,'value'=>'', 'autoload'=>0),
    //         array('option_id'=>331,'value'=>'', 'autoload'=>1)
    //     );
    //     foreach ($default_options as $op) {
    //         $op['branch_id']=$id;
    //         $this->db->insert(db_prefix() . 'branch_options', $op);
    //     }

    // }
}
?>